--This is used to find the colonies each character belongs to
CREATE OR REPLACE TABLE XC3_CHARACTERS AS(
WITH HTML_1 AS (

SELECT URL,VALUE AS SPLIT1,CAST(TRIM(RTRIM(REGEXP_REPLACE(REGEXP_SUBSTR(URL,'wiki/(.*)',1,1,'e'),'_',' '),'(XC3)')) AS VARCHAR(255)) AS COLONY,REGEXP_REPLACE(HTMLCONTENT,'\n','') AS HTML_CONTENT
FROM XC3_CHARACTERS_URL,
LATERAL SPLIT_TO_TABLE(HTML_CONTENT,'</span></h2>')
)
,
CHARACTER_LIST AS (
SELECT *,REGEXP_SUBSTR(VALUE,'<a href="/wiki/\\w+" title="\\w+">\\w+</a>') AS CHARACTER,REGEXP_LIKE(VALUE,'<ul>'),REGEXP_SUBSTR(CHARACTER,'wiki/(\\w+)',1,1,'e') AS CHARA,
REGEXP_SUBSTR(VALUE,'</a> (\\(\\w+\\))',1,1,'e') AS CHARACTER_ROLE,
CASE WHEN COLONY = 'Keves Castle' AND CHARA = 'Colony' THEN 'Melia'
ELSE CHARA END AS CHARACTER1,
CASE WHEN CHARACTER1 = 'Melia' OR CHARACTER1 = 'Nia' OR CHARACTER1 = 'Fiona' OR CHARACTER1 = 'Triton' AND COLONY = 'Colony 15' THEN '(commander)'
ELSE CHARACTER_ROLE END AS CHARACTER_ROLES
FROM HTML_1, 
LATERAL SPLIT_TO_TABLE(SPLIT1,'</li>')
WHERE CHARACTER IS NOT NULL)

-- SELECT *
-- FROM CHARACTER_LIST;
, CHARACTER_NEAR AS (

SELECT CAST(COLONY AS VARCHAR(255)) AS COLONY,CHARACTER1, CHARACTER_ROLES
FROM (
SELECT COLONY,CHARACTER1, CHARACTER_ROLES
FROM CHARACTER_LIST
WHERE CHARACTER1 NOT IN('N','Colony','Aionios','Swordmarch','Keves','Ouroboros','Castle')


UNION

SELECT 'Nopon Caravans' AS COLONY, SPLIT_PART(NOPONN,'.',2) AS CHARACTERS,NULL AS CHARACTER_ROLES
FROM NOPON
WHERE CHARACTERS != ''


UNION

SELECT 'City' AS COLONY, 'Monica' AS CHARACTER,'(commander)' AS CHARACTER_ROLE

UNION

SELECT 'City' AS COLONY, 'Ghondor' AS CHARACTER,'(commander)' AS CHARACTER_ROLE

UNION

SELECT 'Colony Omega' AS COLONY, 'Mio' AS CHARACTER,'(commander)' AS CHARACTER_ROLE

UNION

SELECT 'Colony Omega' AS COLONY, 'Miyabi' AS CHARACTER,'(commander)' AS CHARACTER_ROLE

UNION

SELECT 'Colony 5' AS COLONY, 'Eunie' AS CHARACTER,'(commander)' AS CHARACTER_ROLE

UNION

SELECT 'Colony 9' AS COLONY, 'Lanz' AS CHARACTER,'(commander)' AS CHARACTER_ROLE

UNION

SELECT 'Colony Gamma' AS COLONY, 'Sena' AS CHARACTER,'(commander)' AS CHARACTER_ROLE

UNION

SELECT 'Keves Castle' AS COLONY, 'Noah' AS CHARACTER,'(commander)' AS CHARACTER_ROLE

UNION

SELECT 'Lost Colony' AS COLONY, 'Taion' AS CHARACTER,'(commander)' AS CHARACTER_ROLE

UNION

SELECT 'Lost Colony' AS COLONY, 'Taion' AS CHARACTER,'(commander)' AS CHARACTER_ROLE

UNION

SELECT 'City' AS COLONY, 'Gray' AS CHARACTER,'(commander)' AS CHARACTER_ROLE

UNION

SELECT 'Nopon Caravans' AS COLONY, 'Ino' AS CHARACTER,'(commander)' AS CHARACTER_ROLE

UNION

SELECT 'Colony Gamma' AS COLONY, 'Manana' AS CHARACTER,'(commander)' AS CHARACTER_ROLE
)
)

SELECT CHARACTER1,CHARACTER_ROLES,
CASE WHEN CHARACTER1 IN('Triton','Lhukavu','Saoru','Orson','Pergas','Ronja','Api','Torto','Kio') THEN 'Colony 15'
WHEN CHARACTER1 = 'Isurd' THEN 'Colony Lambda'
WHEN CHARACTER1 = 'Ashera' THEN 'Colony 11'
WHEN CHARACTER1 = 'Alexandria' THEN 'Colony Iota'
WHEN CHARACTER1 = 'Ethel' THEN 'Colony 4'
WHEN CHARACTER1 = 'Mwamba' THEN 'Colony 9'
WHEN CHARACTER1 = 'Nimue' THEN 'Lost Colony'
ELSE COLONY END AS COLONY
FROM CHARACTER_NEAR

);

SELECT DISTINCT *
FROM XC3_CHARACTERS;

CREATE OR REPLACE TABLE HERO_PER_COLONY AS (
SELECT COLONY,CAST(CHARACTER1 AS VARCHAR(255))AS HERO,ASCENTION_QUEST_NAME
FROM XC3_CHARACTERS AS A
LEFT JOIN HERO AS B ON A.CHARACTER1 = B.HEROS
WHERE CHARACTER_ROLES = '(commander)' OR CHARACTER_ROLES = '(Commander)'
);