-- Creating ER diagram to track tables for when view is being created
SELECT *
FROM XC3_COLONIES;

SELECT COUNT(CHARACTER1),CHARACTER1
FROM CHARACTERS
GROUP BY CHARACTER1
HAVING COUNT(CHARACTER1) > 1;

SELECT *
FROM XC3_ASCENTION_PREQUISIT_QUESTS;

SELECT *
FROM XC3_REGIONS;

SELECT *
FROM REGIONAL_COLONY_LOCATIONS;

SELECT *
FROM HERO_INFO;

SELECT *
FROM TIL_PORTFOLIO_PROJECTS.CHARALAMBOS_PERSONAL_PROJECT.XC3_CHARACTERS;

SELECT *
FROM TIL_PORTFOLIO_PROJECTS.CHARALAMBOS_PERSONAL_PROJECT.XC3_HERO_QUESTS;

SELECT *
FROM TIL_PORTFOLIO_PROJECTS.CHARALAMBOS_PERSONAL_PROJECT.XC3_TEST_QUESTS;

SELECT *
FROM TIL_PORTFOLIO_PROJECTS.CHARALAMBOS_PERSONAL_PROJECT.ASCENTION_QUEST_CONDITIONS;

SELECT *
FROM HERO_INFO_URL;

SELECT *
FROM XC3_CHARACTERS;


SELECT *
FROM HERO_PER_COLONY;

ALTER TABLE XC3_REGIONS ADD PRIMARY KEY (REGION);

ALTER TABLE XC3_COLONIES ADD FOREIGN KEY (REGION) REFERENCES XC3_REGIONS(REGION);
ALTER TABLE REGIONAL_COLONY_LOCATIONS ADD FOREIGN KEY (REGION) REFERENCES XC3_REGIONS(REGION);

ALTER TABLE REGIONAL_COLONY_LOCATIONS ADD PRIMARY KEY (COLONIES);

ALTER TABLE XC3_CHARACTERS ADD FOREIGN KEY (COLONY) REFERENCES REGIONAL_COLONY_LOCATIONS(COLONIES);
ALTER TABLE XC3_COLONIES ADD FOREIGN KEY (COLONY) REFERENCES REGIONAL_COLONY_LOCATIONS(COLONIES);
ALTER TABLE HERO_PER_COLONY ADD FOREIGN KEY (COLONY) REFERENCES REGIONAL_COLONY_LOCATIONS(COLONIES);


ALTER TABLE XC3_COLONIES ADD PRIMARY KEY (COLONY);
-- THIS IS TO SHOW ONE TO ONE RELATIONSHIP, THEN JUST DO FOR ONE OF THEM
ALTER TABLE REGIONAL_COLONY_LOCATIONS ADD FOREIGN KEY (COLONIES) REFERENCES XC3_COLONIES(COLONY);
ALTER TABLE HERO_PER_COLONY ADD FOREIGN KEY (COLONY) REFERENCES XC3_COLONIES(COLONY);

ALTER TABLE HERO_PER_COLONY ADD PRIMARY KEY (HERO);

ALTER TABLE HERO_INFO ADD FOREIGN KEY (HEROS) REFERENCES HERO_PER_COLONY(HERO);
ALTER TABLE ASCENTION_QUEST_CONDITIONS ADD FOREIGN KEY (HEROS) REFERENCES HERO_PER_COLONY(HERO);
ALTER TABLE XC3_ASCENTION_PREQUISIT_QUESTS ADD FOREIGN KEY (HEROS) REFERENCES HERO_PER_COLONY(HERO);
ALTER TABLE XC3_HERO_QUESTS ADD FOREIGN KEY (HERO) REFERENCES HERO_PER_COLONY(HERO);
// seems like 1-1


ALTER TABLE XC3_TEST_QUESTS ADD PRIMARY KEY (QUEST_NAME);

ALTER TABLE XC3_HERO_QUESTS ADD FOREIGN KEY (HERO_QUEST) REFERENCES XC3_TEST_QUESTS (QUEST_NAME);
ALTER TABLE XC3_ASCENTION_PREQUISIT_QUESTS ADD FOREIGN KEY (QUEST) REFERENCES XC3_TEST_QUESTS (QUEST_NAME);


ALTER TABLE XC3_TEST_QUESTS ADD PRIMARY KEY (HOW_TO_ACCEPT_QUEST);

ALTER TABLE XC3_CHARACTERS ADD FOREIGN KEY (CHARACTER1) REFERENCES XC3_TEST_QUESTS (QUEST_NAME) ;

--ALTER TABLE XC3_HERO_QUESTS DROP FOREIGN KEY(HERO_QUEST);



ALTER TABLE HERO_INFO_URL ADD PRIMARY KEY (URL);

ALTER TABLE XC3_COLONIES ADD FOREIGN KEY (IMAGES) REFERENCES HERO_INFO_URL (URL);
ALTER TABLE HERO_INFO ADD FOREIGN KEY (IMAGES) REFERENCES HERO_INFO_URL (URL);

--ALTER TABLE XC3_HERO_QUESTS DROP FOREIGN KEY (HERO);
ALTER TABLE HERO_PER_COLONY DROP FOREIGN KEY (COLONY);

// One to one on prerequisit conditions but joins to all quests 

SELECT *
FROM XC3_FULL_DATASET;
