CREATE OR REPLACE TABLE HERO_INFO AS (

SELECT DISTINCT HTMLCONTENT
FROM(TIL_PORTFOLIO_PROJECTS.CHARALAMBOS_PERSONAL_PROJECT.MYHTMLDATAASCENTION);

-- CREATE OR REPLACE TABLE HERO_INFO AS (

WITH HTML_REPLACE AS (
SELECT URL, REGEXP_REPLACE(HTMLCONTENT,'\\n','') AS HTML,
RTRIM(REGEXP_SUBSTR(HTML,'\\w+&#39'),'&#39') AS HERO,SPLIT_PART(REGEXP_SUBSTR(HTML,'Ascension Quest:.*?Walkthrough'),'|',1) AS ASCENTION_QUEST,
ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS ORDER1
FROM TIL_PORTFOLIO_PROJECTS.CHARALAMBOS_PERSONAL_PROJECT.MYHTMLDATAASCENTION
ORDER BY ORDER1)

,

HTML_SPLIT1 AS (

SELECT HTML,VALUE AS SPLIT1,URL,ASCENTION_QUEST,HERO,ORDER1,ROW_NUMBER() OVER (ORDER BY (ORDER1)) AS ORDER2
FROM HTML_REPLACE,
LATERAL SPLIT_TO_TABLE(HTML,'<\/h3')

)

,
HTML_SPLIT2 AS (

SELECT SPLIT1,URL,HTML,VALUE AS SPLIT2,HERO,ASCENTION_QUEST,ORDER1,ORDER2,ROW_NUMBER() OVER (ORDER BY (ORDER2)) AS ORDER3
FROM HTML_SPLIT1,
LATERAL SPLIT_TO_TABLE(SPLIT1,'<\/h4>')
)

-- SELECT *
-- FROM HTML_SPLIT2;

,

HTML_SPLIT_3 AS (

SELECT URL,VALUE AS SPLIT3,REGEXP_SUBSTR(SPLIT2,'Role') AS TABLE_HEADER,SPLIT2,ORDER1,ORDER2,ORDER3,ROW_NUMBER() OVER (ORDER BY (ORDER3)) AS ORDER4,
CASE WHEN CONTAINS(SPLIT3,'><table class') THEN 1
ELSE NULL END AS TABLE_HEADER_PART_2,
CASE WHEN HERO = 'Miyabi' AND REGEXP_REPLACE(ASCENTION_QUEST,'&#39;','') NOT LIKE '%Walkthrough%' THEN 'Mio'
ELSE HERO END AS HEROS,
CASE WHEN HEROS = 'Mio' THEN 'Ascension Quest: Side Story: Mio Walkthrough '
ELSE REGEXP_REPLACE(ASCENTION_QUEST,'&#39;','') END AS ASCENTION_QUEST_NAME
-- ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS ORDER1
FROM HTML_SPLIT2,
LATERAL SPLIT_TO_TABLE(SPLIT2,'</td>')
)

-- SELECT *
-- FROM HTML_SPLIT_3;
,

HTML_HERO_TABLE AS (

SELECT URL,TABLE_HEADER,ASCENTION_QUEST_NAME,SPLIT2,SPLIT3,ORDER1,ORDER2,ORDER3,ORDER4,HEROS,
-- TABLE_HEADER_PART_2 = 1
--    OR LEAD(TABLE_HEADER_PART_2, 1) OVER (ORDER BY (ORDER4)) = 1
--    OR LEAD(TABLE_HEADER_PART_2, 2) OVER (ORDER BY (ORDER4)) = 1
--    AS HERO_TABLE,
   CONTAINS(SPLIT3,'img') AS IMAGE_FILTER
FROM HTML_SPLIT_3
)

SELECT *
FROM HTML_HERO_TABLE;

-- SELECT *,
-- CASE 
-- WHEN HEROS = 'Mio' AND STUFF = 'Troubadour'
-- THEN NULL 
-- ELSE STUFF END AS CORRECTION
-- FROM HTML_HERO_TABLE
-- WHERE CORRECTION IS NOT NULL AND IMAGE_FILTER = TRUE AND TABLE_HEADER IS NOT NULL;



-- SELECT *,CONTAINS(SPLIT3,'  </tr></table>') AS HI
-- FROM HTML_HERO_TABLE
-- WHERE TABLE_HEADER IS NOT NULL AND IMAGE_FILTER = TRUE AND HI = FALSE

-- WHERE TABLE_HEADER = 'Role' AND IMAGE_FILTER = TRUE;
-- WHERE TABLE_HEADER IS NOT NULL
-- ORDER BY HEROS;
,

HTML_HERO_EXTRACTION AS (
SELECT LTRIM(REGEXP_SUBSTR(REGEXP_REPLACE(SPLIT3,' ',''),'/>\\w+'),'\/>') AS STUFF,
REGEXP_SUBSTR(SPLIT3,'img.game8.co/\\d+/\\w+.png/show') AS IMAGES,URL,TABLE_HEADER,ASCENTION_QUEST_NAME,SPLIT2,SPLIT3,ORDER1,ORDER2,ORDER3,ORDER4,HEROS,
IMAGE_FILTER
FROM HTML_HERO_TABLE
WHERE STUFF IS NOT NULL AND IMAGE_FILTER = TRUE AND TABLE_HEADER IS NOT NULL
//AND HERO_TABLE = TRUE
)

-- SELECT *
-- FROM HTML_HERO_EXTRACTION;
,

HTML_NEW AS (
SELECT IMAGES,ASCENTION_QUEST_NAME,
CASE 
WHEN HEROS = 'Mio' AND STUFF = 'Troubadour'
THEN NULL 
ELSE STUFF END AS HERO_INFO,HEROS
FROM HTML_HERO_EXTRACTION
WHERE HERO_INFO IS NOT NULL
)
SELECT IMAGES,CAST(ASCENTION_QUEST_NAME AS VARCHAR(255)) AS ASCENTION_QUEST_NAME ,HERO_INFO,CAST(HEROS AS VARCHAR(255)) AS HEROS
FROM HTML_NEW

UNION ALL

SELECT 'img.game8.co/3550198/ce53e6cfefaca0878eefa2275d0ef119.png/show' AS IMAGES, NULL AS ASCENTION_QUEST_NAME, 'Ethel' AS HERO_INFO, 'Ethel' AS HEROS

UNION ALL

SELECT 'j-img.game8.co/7028723/753fa151b133ec70a6222bbf99dba7fc.png/show' AS IMAGES, NULL AS ASCENTION_QUEST_NAME, 'Flash Fencer' AS HERO_INFO, 'Ethel' AS HEROS

UNION ALL

SELECT 'img.game8.co/3554695/72c9d76ee6357debb42e37c7cd1b0c61.png/show' AS IMAGES, NULL AS ASCENTION_QUEST_NAME, 'Attacker' AS HERO_INFO, 'Ethel' AS HEROS

-- );

SELECT *
FROM HERO_INFO;

-- SELECT *
-- FROM(
-- SELECT HEROS,ASCENTION_QUEST_NAME,STUFF,
-- CASE WHEN HERO_COUNT = 3 THEN 'Role'
-- WHEN HERO_COUNT = 2 THEN 'Class'
-- WHEN HERO_COUNT = 1 THEN 'Character'
-- ELSE NULL END AS HEADER
-- FROM HTML_NEW
-- ORDER BY HEROS,HERO_COUNT)

-- PIVOT(MAX(STUFF) FOR HEADER IN ('Role','Character','Class') )
-- ;

CREATE OR REPLACE TABLE HERO_INFO_URL (
URL VARCHAR(255)
);


SELECT URL AS IMAGES, ASCENTION_QUEST_NAME,HERO_INFO,HEROS
FROM (
SELECT URL,REGEXP_SUBSTR(URL,'m/(\\w+)',1,1,'e') AS HI
FROM HERO_INFO_URL) AS A

INNER JOIN 

(
SELECT IMAGES AS IM,ASCENTION_QUEST_NAME,HERO_INFO,HEROS,SPLIT_PART(SPLIT_PART(IMAGES,'/',3),'.',1) AS HI
FROM HERO_INFO) AS B

ON A.HI = B.HI;
;

SELECT URL AS IMAGES,COLONY,REGION
FROM (
SELECT *,REGEXP_SUBSTR(URL,'m/(\\w+)',1,1,'e') AS HI
FROM HERO_INFO_URL) AS A

INNER JOIN 

(
SELECT IMAGES AS IM1,COLONY,REGION,SPLIT_PART(SPLIT_PART(IMAGES,'/',5),'.',1) AS HI
FROM XC3_COLONIES) AS B

ON A.HI = B.HI;

SELECT *
FROM XC3_COLONIES;

SELECT *
FROM HERO_INFO;

SELECT *
FROM XC3_ASCENTION_PREQUISIT_QUESTS;